name: API tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: api/package-lock.json

      - name: Debug paths
        run: |
          pwd
          ls -la
          ls -la api
          cat api/package.json

      - name: Install deps
        run: npm ci
        working-directory: api

      - name: Run tests
        run: npm test
        working-directory: api
        env:
          DATABASE_URL_TEST: ${{ secrets.DATABASE_URL_TEST }}
